export const GET_CURRENT_USER = "GET_CURRENT_USER";
export const GET_CURRENT_USER_VALUE = "GET_CURRENT_USER_VALUE";
export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";
export const GET_CURRENT_USER_FAILURE = "GET_CURRENT_USER_FAILURE";

export const GET_DROPDOWN_CAT = "GET_DROPDOWN_CAT";
export const GET_DROPDOWN_CAT_SUCCESS = "GET_DROPDOWN_CAT_SUCCESS";
export const GET_DROPDOWN_CAT_FAILURE = "GET_DROPDOWN_CAT_FAILURE";

export const GET_HOME_CAT = "GET_HOME_CAT";
export const GET_HOME_CAT_SUCCESS = "GET_HOME_CAT_SUCCESS";
export const GET_HOME_CAT_FAILURE = "GET_HOME_CAT_FAILURE";

export const GET_CHANGE_CAT = "GET_CHANGE_CAT";

export const CHOOSE_CAT_LOADING = "CHOOSE_CAT_LOADING";
export const CHOOSE_CAT_SUCCESS = "CHOOSE_CAT_SUCCESS";
export const CHOOSE_CAT_FAILURE = "CHOOSE_CAT_FAILURE";
export const CHOOSE_CAT_FAVOURITE = "CHOOSE_CAT_FAVOURITE";
export const CHOOSE_NEXT_PAGE = "CHOOSE_NEXT_PAGE";

export const FAVOURITE_CAT_LOADING = "FAVOURITE_CAT_LOADING";
export const FAVOURITE_CAT_SUCCESS = "FAVOURITE_CAT_SUCCESS";
export const FAVOURITE_CAT_FAILURE = "FAVOURITE_CAT_FAILURE";
export const GET_FAVOURITES = "GET_FAVOURITES";
export const DELETE_FAVOURITES = "DELETE_FAVOURITES";
